### ISSUE TITLE
Thanks! 

### ISSUE THREAD

**Issue by wylansford** [X2ISPANDA/lrc-share#4]
Hi! I don't have any issues to add, and I'm not able to contribute to the project. But I just want to say: Thank you so much for this! I'm still in the early stages of learning mandarin, but I have fallen in love with listening to some of these artists like Fac d-12, 龙胆紫，阴三儿， dirty moss, and a few others. Without the lyrics in front of me, it is pretty difficult for me to decipher what they are saying sometimes. I've spent years listening to them, but I still can't always understand what they mean in some songs.

It's sad to me that the songs can't be more widespread, but I just wanted to let you know that this project has helped me a lot. There is at least one person who appreciates your work! :D

(Sorry, I accidentally left this same issue on the wrong repository before :p) 

你好！我没有任何问题要补充，我也不能为项目做贡献。但我只想说。非常感谢你！我还在学习普通话的早期阶段。我还在学习普通话的早期阶段，但我已经爱上了听其中一些艺术家的歌，比如Fac d-12，龙胆紫，阴三儿，dirty moss，以及其他一些艺术家。没有歌词在我面前，我有时很难解读他们在说什么。我花了好几年时间听他们的歌，但我仍然不能总是理解他们在某些歌曲中的意思。

对我来说，这些歌曲不能得到更广泛的传播是很可悲的，但我只想让你知道，这个项目对我帮助很大。至少有一个人在欣赏你的工作! :D

(对不起，我之前不小心把这个同样的问题留在了错误的存储库上 :p)

**Comment by X2ISPANDA** [comment]
谢谢您，看到您的感谢信我真的十分激动，现在我已经把这个项目放到lrcshare.com网站上了，欢迎到网站上进行观看，thanks a lot.

**Comment by JluoMixing** [comment]
dope bro，Your project has been of great help to me, and I hope I can assist you to the best of my ability
太牛逼了瓷，你的项目对我帮助很大，希望我能在力所能及下帮助你

**Comment by X2ISPANDA** [comment]
感谢兄弟的支持
